name: Build
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
env:
  APP_NAME: icy_play
  CARGO_TERM_COLOR: always
jobs:
  build_windows:
    runs-on: windows-latest
    env:
      FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
    steps:
    - uses: actions/checkout@v3

    - name: Build exe
      run: |      
        cargo build --release
    - name: Copy exe
      run: cp ".\target\release\${{ env.APP_NAME }}.exe" .
    - name: 'Upload plain exe'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}_${{ env.VERSION }}_windows_exe
        path: |
          .\${{ env.APP_NAME }}.exe
          file_id.diz
